Implement SheetHolder and cross-sheet referencing
lightsheet-team/lightsheet pull request #117
Opened 2024-04-12 23:02 UTC by Fluglow

**SheetHolder**
* Implement `SheetHolder` as a singleton stored in the window object
* Only track `Lightsheet` objects in `SheetHolder` -> don't allow `Sheet` objects to exist without `Lightsheet`
    * `SheetHolder` would otherwise need to track *both* `Lightsheet` objects and "unattached" `Sheet` objects

**Sheet / ExpressionHandler**
* Add expression parsing for referring to other Sheets' cells (`=SheetName!A1`)
* Add `SheetKey` and add it to types used in expression parsing and cell reference handling
* Update cell updating and reference handling logic to account for cells in different sheets
    * When a change happens in a `Sheet`, that `Sheet` is responsible for updating all other `Sheet` objects
* Move `cellData` to `SheetHolder`
    * This simplifies lookups with multiple sheets since `CellKeys` are independent

**Lightsheet**
* Add sheet name to `LightsheetOptions`, default null data to `[]`
* Allow `Lightsheet` to be instantiated without UI

**Refactoring**
* Make type `{ columnPosition, rowPosition }` shared as `Coordinate` in `utils/common.types.ts` 
    * Should this file be somewhere else / called something else?
* Move `utils` folder under `src`

2024-04-13 11:03 UTC, Yousif-FJ commented
Here is my opinion on this and why I think this is problematic:

#### sheet holder containing `cellData`

- `Sheet` containing `SheetHolder` when the hierarchy should be the other way around.
- `SheetHolder` holding `cellData` when we expect it to hold `Sheet`.
- `SheetHolder` holding `LightSheet` when we expect to hold `Sheet`.
- Extreme coupling between `Sheet` and `SheetHolder` while `SheetHolder` should only be necessary when evaluating expression.


My suggestion, would be to go back to something similar to the structure we agreed on:
- `sheetHolder` holding sheet 
- We create a new class called `EvaluationContext` which a `LightSheet` level object that encapsulate `expressionHandler` and the logic of evaluating math, and contains `sheetHolder`
- Refactor resolve cell to do reference handling from the new class.

I know this might be a big change from what you did, but I have to give my opinion.

2024-04-13 11:10 UTC, Yousif-FJ commented on src/core/structure/sheetHolder.ts
> +  }
I would private the contractor and create a static function called something like `GetOrCreateSheetHolder`, which, as you might have guessed, checks if the Holder exist, if not, call the private constructor which creates `sheetHolder` normally. 

In the current state, it is extremely unexpected that the constructor doesn't actually create a new instance.

2024-04-13 13:42 UTC, Fluglow commented
@Yousif-FJ 
I think your proposals should be implementable from this. I chose this easier route since separating logic from `Sheet` proved to be quite tricky, but it should be easier from this stage. The main issue was that we want to keep most methods private in `Sheet`, and separating logic easily leads to having to call these internal methods from elsewhere. 

`SheetHolder` containing `cellData` is akin to the structure of having a separate `DataManager`, but they are just combined now. I again see the benefit of holding `cellData` separate from `Sheet`, since cell information doesn't need to be indexed by anything else (holding it in `Sheet` is essentially indexing by `SheetKey`). `Cell` objects are also cross-sheet by nature as they can hold keys from multiple different sheets, so having them in a broader context seems more correct.

2024-04-14 15:32 UTC, rafinutshaw requested changes

2024-04-14 15:32 UTC, rafinutshaw commented on index.js
> +  document.getElementById("lightsheet"),
targetelement should be the first parameter. because target element is a required parameter. the whole options object should be optional

2024-04-14 15:32 UTC, rafinutshaw commented on src/core/structure/sheetHolder.ts
> +      return window.sheetHolder;
why do you need to return a value from a constructor?

2024-04-14 15:35 UTC, rafinutshaw commented
This excellent work @Fluglow

2024-04-14 15:37 UTC, rafinutshaw commented
When i try to refer to a sheet that does not exist. it show show an error just like in excel. instead it is clearing the field

2024-04-17 13:58 UTC, rafinutshaw approved these changes

2024-04-17 14:08 UTC, Yousif-FJ approved these changes

2024-04-17 14:09 UTC, merged