UI tool bar
lightsheet-team/lightsheet pull request #77
Opened 2024-03-20 14:36 UTC by amy-hoangg

Create types for tool bar
Create a tool bar element inside div id="lightsheet"
Use Google API for icons placeholder in tool bar https://fonts.google.com/icons
Add styles for each item in tool bar
Note: the code is based on what JS Spreadsheet has

2024-03-22 14:20 UTC, rafinutshaw requested changes

2024-03-22 14:20 UTC, rafinutshaw commented on index.js
>    },
The user will also provide a boolean of toolbar visibility, and the dom(optional) he wants the toolbar to mound into.
example,

const lightsheet = new Lightsheet(document.getElementById("lightsheet"), {
  data,
  columns,
 {
showToolbar: true/false,
items: toolbar,
element: document.getElementById("toolbar-dom-id")
},
  onCellChange: (colIndex, rowIndex, newValue) => {
    console.log(colIndex, rowIndex, newValue);
  },
}
//if user wants to make the toolbar visible/imvisible, he can call this method anytime
lightsheet.showToolbar(true/false);

2024-03-22 14:20 UTC, rafinutshaw commented on index.js
>    },
You can name your methods and property names as you see fit

2024-03-28 13:04 UTC, rafinutshaw approved these changes

2024-04-11 14:19 UTC, Fluglow reviewed
Left some notes, just minor things :+1:

2024-04-11 14:19 UTC, Fluglow commented on src/ui/render.ts
> +    }
This if-block can be inverted to reduce nesting.

2024-04-11 14:19 UTC, Fluglow commented on src/ui/render.ts
> +  }
If we skip creating `this.toolBarDom` as I suggest in an earlier comment, this method should check for `toolBarOptions`. 
The method can also be simplified to `this.toolBarDom.style.display = isShown ? "flex" : "none";`

2024-04-11 14:19 UTC, Fluglow commented on tests/ui/toolBar.test.ts
> +    expect(toolBarElement!.children.length).toBe(13);
Maybe compare against `ToolbarItems.length` instead?

2024-04-13 18:57 UTC, rafinutshaw commented
> Left some notes, just minor things 👍

Good catch. Resolved them all. @Fluglow

2024-04-14 06:16 UTC, merged