Editability
lightsheet-team/lightsheet pull request #86
Opened 2024-03-28 13:32 UTC by amy-hoangg

1. Create isReadOnly property in the lightSheet options
2. Parse the isReadOnly into UI
3. Create a function changeReadOnly in the lightsheet so that user can call it
4. Whenever in readonly mode, the input tag for each cell has the property readonly

2024-03-28 13:50 UTC, rafinutshaw requested changes

2024-03-28 13:50 UTC, rafinutshaw commented on src/main.ts
> +  changeReadOnly(isReadOnly: boolean) {
Rename to setReadOnly

2024-03-28 13:50 UTC, rafinutshaw commented on src/ui/render.ts
> +  changeReadOnly(readonly: boolean) {
Rename to setReadOnly

2024-04-06 15:16 UTC, rafinutshaw commented
Added a minor fix, everything else seems good. 
Kindly resolve the conflict so i can approve.

Thanks!

2024-04-07 11:15 UTC, rafinutshaw requested changes

2024-04-07 11:15 UTC, rafinutshaw commented on tests/ui/initialtable.test.ts
Whoops. I think you accidently deleted this file :')

2024-04-07 18:39 UTC, amy-hoangg commented on tests/ui/initialtable.test.ts
I have added it again. Sorry for deleting it.

2024-04-07 18:43 UTC, amy-hoangg commented on tests/ui/initialtable.test.ts
Also there is some error in the test initialtabletable.test.ts. I have not changed anything in it since I merged from main and may be the problem stemmed from main?

2024-04-08 10:07 UTC, amy-hoangg commented on tests/ui/initialtable.test.ts
I got it. Thanks a lot!

2024-04-08 10:22 UTC, amy-hoangg commented on tests/ui/initialtable.test.ts
I am wondering should I still keep the isReadOnly as compulsory?

2024-04-08 10:23 UTC, rafinutshaw commented on tests/ui/initialtable.test.ts
no, it should be optional is a default value of false.

2024-04-08 10:24 UTC, Fluglow commented on tests/ui/initialtable.test.ts
It should probably be optional with `false` as the default, as that's the pattern for the other properties.

2024-04-08 11:08 UTC, Fluglow approved these changes
lgtm :+1:

2024-04-08 11:34 UTC, amy-hoangg commented
> lgtm 👍

2024-04-08 12:33 UTC, rafinutshaw approved these changes

2024-04-08 13:02 UTC, merged